# Paths
dataset_dir: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Floor_Plan_Localization/data/test_data_set_full/structured3d_perspective_full'
desdf_path: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Floor_Plan_Localization/data/test_data_set_full/desdf'
prob_vol_save_dir: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Floor_Plan_Localization/data/test_data_set_full/prob_vols'
log_dir_depth: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Floor_Plan_Localization/modules/Final_wights/depth/final_depth_model_checkpoint.ckpt'
log_dir_semantic: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Floor_Plan_Localization/modules/Final_wights/semantic/final_semantic_model_checkpoint.ckpt'

# Dataset parameters
L: 0

# Depth network parameters
D: 128
d_min: 0.1
d_max: 15.0
d_hyp: -0.2

# Semantic network parameters
num_classes: 4

# Evaluation parameters
start_scene: 3250
end_scene: 3251